xdotool windowactivate 44040195
xdotool type Edwin
xdotool key Tab
xdotool type Rhodes
xdotool key Tab
xdotool type 1976-03-10
xdotool key Tab
xdotool type 4976
xdotool key space
xdotool type Rainbow
xdotool key space
xdotool type Drive
xdotool key space
xdotool key Tab
xdotool type Richfield
xdotool key space
xdotool key Tab
xdotool type OH
xdotool key Tab
xdotool type 44286
xdotool key Tab
xdotool type EdwinPRhodes@cuvox.de
xdotool key Tab
xdotool type 330-523-6293
