xdotool windowactivate 46137347
xdotool type James
xdotool key Tab
xdotool type Taylor
xdotool key Tab
xdotool type 1962-11-09
xdotool key Tab
xdotool type 896
xdotool key space
xdotool type Trymore
xdotool key space
xdotool type Road
xdotool key space
xdotool key Tab
xdotool type Byron
xdotool key space
xdotool key Tab
xdotool type MN
xdotool key Tab
xdotool type 55920
xdotool key Tab
xdotool type JamesSTaylor@dayrep.com
xdotool key Tab
xdotool type 507-775-9794
