xdotool windowactivate 44040195
xdotool type Florence
xdotool key Tab
xdotool type Deloatch
xdotool key Tab
xdotool type 1963-06-24
xdotool key Tab
xdotool type 2481
xdotool key space
xdotool type Stutler
xdotool key space
xdotool type Lane
xdotool key space
xdotool key Tab
xdotool type Erie
xdotool key space
xdotool key Tab
xdotool type PA
xdotool key Tab
xdotool type 16505
xdotool key Tab
xdotool type FlorenceJDeloatch@fleckens.hu
xdotool key Tab
xdotool type 814-504-1885
