# Generated by Django 3.0.6 on 2020-06-01 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joad_sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True)),
                ('state', models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('closed', 'closed')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=3)),
                ('post_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('level', models.CharField(choices=[('standard', 'Standard'), ('family', 'Family'), ('joad', 'JOAD'), ('senior', 'Senior')], max_length=20)),
                ('reg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('benefactor', models.BooleanField(default=False)),
                ('verification_code', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('pay_code', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.CharField(max_length=50, null=True)),
                ('reg_date', models.DateField()),
                ('checkout_created_time', models.DateTimeField()),
                ('checkout_id', models.CharField(max_length=50, null=True)),
                ('order_id', models.CharField(max_length=50, null=True)),
                ('location_id', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('total_money', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('idempotency_key', models.UUIDField()),
                ('receipt', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pin_scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bow', models.CharField(choices=[('barebow', 'Barebow/Basic Compound/Traditional'), ('olympic', 'Olympic Recurve'), ('compound', 'Compound')], max_length=45)),
                ('category', models.CharField(choices=[('joad_indoor', 'JOAD Indoor')], max_length=20)),
                ('distance', models.IntegerField(choices=[(9, 9), (18, 18)])),
                ('target', models.IntegerField(choices=[(40, 40), (60, 60), (80, 80), (122, 122)])),
                ('score', models.IntegerField()),
                ('stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pin_shoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=45, null=True)),
                ('category', models.CharField(choices=[('joad_indoor', 'JOAD Indoor')], max_length=20)),
                ('bow', models.CharField(choices=[('barebow', 'Barebow/Basic Compound/Traditional'), ('olympic', 'Olympic Recurve'), ('compound', 'Compound')], max_length=45)),
                ('shoot_date', models.DateField()),
                ('distance', models.IntegerField()),
                ('target', models.IntegerField(choices=[(40, 40), (60, 60), (80, 80), (122, 122)])),
                ('prev_stars', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)])),
                ('stars', models.IntegerField()),
                ('wpa_membership_number', models.IntegerField(null=True)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Membership')),
            ],
        ),
        migrations.CreateModel(
            name='Joad_session_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_status', models.CharField(max_length=20)),
                ('idempotency_key', models.UUIDField(default='2474266f-aad2-4c5c-9015-57ff687a6377')),
                ('mem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.Member')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.Joad_sessions')),
            ],
        ),
    ]
